"use client"

import { useState, useEffect, useCallback } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import { 
  MoreHorizontal, 
  Eye, 
  Download, 
  Trash2, 
  Clock,
  ChevronLeft,
  ChevronRight,
  AlertCircle,
  Thermometer,
  Droplets
} from "lucide-react"
import { cn } from "@/lib/utils"
import type { ScanHistoryItem, Severity } from "@/lib/types"
import { getScanHistory, deleteScanFromHistory, clearScanHistory } from "@/hooks/use-analysis"
import Image from "next/image"

function getSeverityColor(severity: Severity): string {
  switch (severity) {
    case "None":
      return "bg-green-500/10 text-green-700 border-green-500/20"
    case "Mild":
      return "bg-yellow-500/10 text-yellow-700 border-yellow-500/20"
    case "Moderate":
      return "bg-orange-500/10 text-orange-700 border-orange-500/20"
    case "Severe":
      return "bg-red-500/10 text-red-700 border-red-500/20"
    case "Critical":
      return "bg-red-700/10 text-red-800 border-red-700/20"
    default:
      return "bg-muted text-muted-foreground"
  }
}

export function HistoryTable() {
  const [history, setHistory] = useState<ScanHistoryItem[]>([])
  const [currentPage, setCurrentPage] = useState(1)
  const [selectedScan, setSelectedScan] = useState<ScanHistoryItem | null>(null)
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false)
  const [scanToDelete, setScanToDelete] = useState<string | null>(null)
  const [clearAllDialogOpen, setClearAllDialogOpen] = useState(false)
  
  const itemsPerPage = 10

  // Load history from localStorage on mount
  useEffect(() => {
    setHistory(getScanHistory())
  }, [])

  const totalPages = Math.max(1, Math.ceil(history.length / itemsPerPage))
  const startIndex = (currentPage - 1) * itemsPerPage
  const paginatedHistory = history.slice(startIndex, startIndex + itemsPerPage)

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }).format(date)
  }

  const handleDelete = useCallback((id: string) => {
    setScanToDelete(id)
    setDeleteDialogOpen(true)
  }, [])

  const confirmDelete = useCallback(() => {
    if (scanToDelete) {
      deleteScanFromHistory(scanToDelete)
      setHistory(getScanHistory())
      setDeleteDialogOpen(false)
      setScanToDelete(null)
    }
  }, [scanToDelete])

  const handleClearAll = useCallback(() => {
    setClearAllDialogOpen(true)
  }, [])

  const confirmClearAll = useCallback(() => {
    clearScanHistory()
    setHistory([])
    setClearAllDialogOpen(false)
    setCurrentPage(1)
  }, [])

  const handleViewDetails = useCallback((scan: ScanHistoryItem) => {
    setSelectedScan(scan)
  }, [])

  const handleDownloadReport = useCallback((scan: ScanHistoryItem) => {
    const result = scan.fullResult
    if (!result) return

    const report = `
CROPCARE AI - DISEASE ANALYSIS REPORT
=====================================
Date: ${new Date(result.timestamp).toLocaleString()}

CROP INFORMATION
----------------
Crop Type: ${result.cropLabel}

DIAGNOSIS
---------
Disease: ${result.analysis.disease_name}
Confidence: ${result.analysis.confidence}%
Severity: ${result.analysis.severity}

FARMER ADVICE
-------------
${result.analysis.farmer_advice}

TREATMENTS
----------
Organic:
${result.analysis.organic_treatments.map((t, i) => `${i + 1}. ${t}`).join("\n")}

---
Generated by CropCare AI
`
    
    const blob = new Blob([report], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `cropcare-report-${scan.id}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }, [])

  if (history.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5 text-primary" />
            Scan History
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center mb-4">
              <AlertCircle className="h-8 w-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground mb-2">No scans yet</p>
            <p className="text-sm text-muted-foreground">
              Your scan history will appear here after you analyze plant images
            </p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Clock className="h-5 w-5 text-primary" />
            Scan History
          </CardTitle>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleClearAll}
            className="text-destructive hover:text-destructive"
          >
            Clear All
          </Button>
        </CardHeader>
        <CardContent>
          <div className="rounded-lg border overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-16">Image</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Crop</TableHead>
                  <TableHead>Disease</TableHead>
                  <TableHead>Confidence</TableHead>
                  <TableHead>Severity</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paginatedHistory.map((scan) => (
                  <TableRow key={scan.id}>
                    <TableCell>
                      {scan.imageThumb && (
                        <div className="w-10 h-10 rounded-md overflow-hidden bg-muted">
                          <Image
                            src={`data:image/jpeg;base64,${scan.imageThumb}`}
                            alt="Scan thumbnail"
                            width={40}
                            height={40}
                            className="object-cover w-full h-full"
                          />
                        </div>
                      )}
                    </TableCell>
                    <TableCell className="font-medium">
                      <span className="text-sm">{formatDate(scan.timestamp)}</span>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{scan.crop}</Badge>
                    </TableCell>
                    <TableCell>
                      <span className="font-medium">{scan.disease}</span>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <div className="w-12 h-2 bg-muted rounded-full overflow-hidden">
                          <div 
                            className="h-full bg-primary rounded-full"
                            style={{ width: `${scan.confidence}%` }}
                          />
                        </div>
                        <span className="text-sm text-muted-foreground">
                          {scan.confidence}%
                        </span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge className={cn("border", getSeverityColor(scan.severity))}>
                        {scan.severity}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="h-8 w-8">
                            <MoreHorizontal className="h-4 w-4" />
                            <span className="sr-only">Open menu</span>
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem 
                            className="gap-2"
                            onClick={() => handleViewDetails(scan)}
                          >
                            <Eye className="h-4 w-4" />
                            View Details
                          </DropdownMenuItem>
                          <DropdownMenuItem 
                            className="gap-2"
                            onClick={() => handleDownloadReport(scan)}
                          >
                            <Download className="h-4 w-4" />
                            Export Report
                          </DropdownMenuItem>
                          <DropdownMenuItem 
                            className="gap-2 text-destructive"
                            onClick={() => handleDelete(scan.id)}
                          >
                            <Trash2 className="h-4 w-4" />
                            Delete
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          {/* Pagination */}
          <div className="flex items-center justify-between mt-4">
            <p className="text-sm text-muted-foreground">
              Showing {startIndex + 1}-{Math.min(startIndex + itemsPerPage, history.length)} of {history.length} scans
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="icon"
                onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                disabled={currentPage === 1}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-sm">
                Page {currentPage} of {totalPages}
              </span>
              <Button
                variant="outline"
                size="icon"
                onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* View Details Dialog */}
      <Dialog open={!!selectedScan} onOpenChange={() => setSelectedScan(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Scan Details</DialogTitle>
          </DialogHeader>
          {selectedScan?.fullResult && (
            <div className="space-y-4">
              <div className="flex gap-4">
                {selectedScan.imageThumb && (
                  <div className="w-24 h-24 rounded-lg overflow-hidden bg-muted flex-shrink-0">
                    <Image
                      src={`data:image/jpeg;base64,${selectedScan.imageThumb}`}
                      alt="Scan image"
                      width={96}
                      height={96}
                      className="object-cover w-full h-full"
                    />
                  </div>
                )}
                <div>
                  <h3 className="font-semibold text-lg">{selectedScan.disease}</h3>
                  <p className="text-sm text-muted-foreground">
                    {selectedScan.crop} - {formatDate(selectedScan.timestamp)}
                  </p>
                  <div className="flex items-center gap-2 mt-2">
                    <Badge className={cn("border", getSeverityColor(selectedScan.severity))}>
                      {selectedScan.severity}
                    </Badge>
                    <span className="text-sm">{selectedScan.confidence}% confidence</span>
                  </div>
                </div>
              </div>

              {selectedScan.weather && (
                <div className="rounded-lg border p-3 bg-muted/30">
                  <p className="text-sm font-medium mb-2">Weather at time of scan</p>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Thermometer className="h-4 w-4" />
                      {selectedScan.weather.temperature}°C
                    </span>
                    <span className="flex items-center gap-1">
                      <Droplets className="h-4 w-4" />
                      {selectedScan.weather.humidity}%
                    </span>
                  </div>
                </div>
              )}

              <div>
                <p className="text-sm font-medium mb-2">Farmer Advice</p>
                <p className="text-sm text-muted-foreground">
                  {selectedScan.fullResult.analysis.farmer_advice}
                </p>
              </div>

              <div>
                <p className="text-sm font-medium mb-2">Organic Treatments</p>
                <ul className="text-sm text-muted-foreground space-y-1">
                  {selectedScan.fullResult.analysis.organic_treatments.map((t, i) => (
                    <li key={i}>{i + 1}. {t}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Scan</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this scan? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete} className="bg-destructive text-destructive-foreground">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Clear All Confirmation Dialog */}
      <AlertDialog open={clearAllDialogOpen} onOpenChange={setClearAllDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Clear All History</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete all scan history? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmClearAll} className="bg-destructive text-destructive-foreground">
              Clear All
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
